// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyeaxwsnnsiveqoxqpys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5ZWF4d3NubnNpdmVxb3hxcHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzMwMTEsImV4cCI6MjA3MTI0OTAxMX0.gVPBc4q3pgArV6ozEfOiTkMMBSEoaWBIqFgRtJl6HXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});